const DASHBOARD_NAV_GROUPS=[
{label:'總覽',items:[['儀表板首頁','./index.html','index.html'],['總控台','./command-center.html','command-center.html'],['健康檢查','./health-check.html','health-check.html'],['每週系統報告','./weekly-system-report.html','weekly-system-report.html']]},
{label:'資料審核',items:[['城市熱點地圖','./map.html','map.html'],['座標審核','./geocoding-review.html','geocoding-review.html'],['CYCC公開資料','./cycc-review.html','cycc-review.html'],['開放資料盤點','./open-data-inventory.html','open-data-inventory.html'],['官方資料審核','./open-data-review.html','open-data-review.html'],['Readiness評分','./open-data-readiness.html','open-data-readiness.html'],['Top10審核任務','./open-data-top10-tasks.html','open-data-top10-tasks.html'],['Crawler規格草稿','./open-data-crawler-specs.html','open-data-crawler-specs.html'],['人工審核工作簿','./open-data-human-review.html','open-data-human-review.html'],['工程審查清單','./open-data-engineering-review.html','open-data-engineering-review.html'],['人工審核執行','./open-data-review-sessions.html','open-data-review-sessions.html'],['審核證據包','./open-data-review-evidence.html','open-data-review-evidence.html'],['審核結果輸入','./open-data-manual-review-results.html','open-data-manual-review-results.html'],['人工審核 SOP','./open-data-manual-review-sop.html','open-data-manual-review-sop.html'],['人工審核工作包','./open-data-manual-review-packets.html','open-data-manual-review-packets.html'],['回填 Patch 草稿','./open-data-manual-review-patches.html','open-data-manual-review-patches.html'],['Day1填寫範例','./open-data-day1-sample-results.html','open-data-day1-sample-results.html'],['影音轉錄審核','./video-review.html','video-review.html'],['會議紀錄審核','./minutes-review.html','minutes-review.html'],['會議紀錄議題','./minutes-issues.html','minutes-issues.html']]},
{label:'內容產出',items:[['每週摘要','./weekly-summary.html','weekly-summary.html'],['政策草稿','./policy-drafts.html','policy-drafts.html'],['社群草稿','./social-drafts.html','social-drafts.html'],['短影音腳本','./video-scripts.html','video-scripts.html'],['拍攝清單','./filming-checklists.html','filming-checklists.html'],['內容排程','./content-schedule.html','content-schedule.html']]},
{label:'發布管理',items:[['公開審核','./public-review.html','public-review.html'],['已核准素材','./approved-materials.html','approved-materials.html'],['每日執行','./daily-execution.html','daily-execution.html']]},
{label:'系統說明',items:[['城市洞察','./insights.html','insights.html'],['資料來源','./sources.html','sources.html'],['方法論','./methodology.html','methodology.html'],['城市週報','./reports.html','reports.html'],['競選官網','https://www.chiayi2026.com/','external',true]]}
].map((g,i)=>({...g,tone:['overview','review','content','publish','system'][i],items:g.items.map(([title,path,file,external])=>({title,path,file,external}))}));
const DASHBOARD_NAV_ITEMS=DASHBOARD_NAV_GROUPS.flatMap(g=>g.items);
const DASHBOARD_DISCLOSURE='本平台資料來自公開資訊、官方資料與原型資料整理。分析結果為城市治理與地方議題研究用途，不代表完整民意調查，也不作為個人評價結論。';
function getCurrentFileName(){return(location.pathname||'').split('/').filter(Boolean).pop()||'index.html'}
function findCurrentGroup(file){return DASHBOARD_NAV_GROUPS.find(g=>g.items.some(i=>i.file===file))}
function makeNavLink(item,file,cls=''){const a=document.createElement('a');a.href=item.path;a.textContent=item.title;a.className=cls;if(item.file===file)a.classList.add('active');if(item.external){a.target='_blank';a.rel='noopener'}return a}
function renderSharedNav(){const nav=document.querySelector('.nav');if(!nav)return;const file=getCurrentFileName();const group=findCurrentGroup(file)||DASHBOARD_NAV_GROUPS[0];nav.className='nav dashboard-nav';nav.textContent='';const main=document.createElement('div');main.className='dashboard-nav-main';DASHBOARD_NAV_GROUPS.forEach(g=>{const a=document.createElement('a');a.href=g.items[0].path;a.textContent=g.label;a.className='dashboard-nav-tab';if(g.label===group.label)a.classList.add('active');main.appendChild(a)});const sub=document.createElement('div');sub.className='dashboard-nav-sub';const label=document.createElement('span');label.className='dashboard-nav-sub-label';label.textContent=group.label;sub.appendChild(label);group.items.forEach(i=>sub.appendChild(makeNavLink(i,file,'dashboard-nav-link')));nav.append(main,sub)}
function renderBreadcrumb(){const b=document.querySelector('[data-render="breadcrumb"]');if(!b)return;const file=getCurrentFileName();const g=findCurrentGroup(file);const item=DASHBOARD_NAV_ITEMS.find(i=>i.file===file);b.textContent=g&&item?`${g.label} / ${item.title}`:'嘉義城市故障分析中心'}
function renderSharedFooter(){if(document.querySelector('.site-footer'))return;const main=document.querySelector('main');if(!main)return;const f=document.createElement('footer');f.className='site-footer';f.innerHTML=`<p>${DASHBOARD_DISCLOSURE}</p>`;main.insertAdjacentElement('afterend',f)}
function injectFooterStyle(){if(document.getElementById('shared-nav-style'))return;const s=document.createElement('style');s.id='shared-nav-style';s.textContent='.site-footer{max-width:1180px;margin:0 auto 42px;padding:0 24px;color:#64748b;font-size:14px}.site-footer p{border-top:1px solid rgba(15,118,110,.18);padding-top:18px}.dashboard-nav{display:grid!important;grid-template-columns:1fr!important;gap:14px!important;margin:0 0 30px!important}.dashboard-nav-main{display:grid!important;grid-template-columns:repeat(5,minmax(0,1fr))!important;gap:12px!important}.dashboard-nav-tab,.dashboard-nav-link{text-decoration:none!important;color:#fff!important;border:1px solid rgba(255,255,255,.34)!important;background:rgba(255,255,255,.12)!important;font-weight:900!important;box-sizing:border-box!important}.dashboard-nav-tab{display:flex!important;align-items:center!important;justify-content:center!important;min-height:54px!important;border-radius:18px!important;font-size:18px!important;line-height:1.15!important;padding:0 18px!important}.dashboard-nav-sub{display:flex!important;gap:10px!important;flex-wrap:wrap!important;align-items:center!important;background:rgba(0,0,0,.12)!important;border-radius:22px!important;padding:12px!important}.dashboard-nav-sub-label,.dashboard-nav-link{display:inline-flex!important;align-items:center!important;justify-content:center!important;height:42px!important;min-height:42px!important;border-radius:999px!important;padding:0 16px!important;font-size:16px!important;line-height:1!important;white-space:nowrap!important}.dashboard-nav-sub-label{color:#fff!important;background:rgba(255,255,255,.22)!important;font-weight:950!important}.dashboard-nav-tab.active,.dashboard-nav-link.active{background:#fff!important;color:#064e3b!important}.dashboard-nav-sub-label.active{background:rgba(255,255,255,.22)!important;color:#fff!important}@media(max-width:640px){.dashboard-nav-main{grid-template-columns:1fr!important}.dashboard-nav-sub-label,.dashboard-nav-link{height:40px!important;min-height:40px!important;font-size:15px!important;padding:0 14px!important}}';document.head.appendChild(s)}
injectFooterStyle();renderSharedNav();renderBreadcrumb();renderSharedFooter();
